# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TechDone
email: josh@techdone.com
description: > # this means to ignore newlines until "baseurl:"
    A blog focusing on AWS, Chef, Ruby, DevOps, Docker and 
    everything inbetween
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://techdone.com" # the base hostname & protocol for your site
github_username:  sniperd
sass:
    load_paths:
        - _sass
        - bootstrap-sass/assets/stylesheets
    style: compressed

# Build settings
markdown: kramdown
